### ISSUE TITLE
Problem with exporting music

### ISSUE THREAD

**Issue by otiskujawa** [ringosham/Lazer-exporter#10]
at the beginning I had a problem only with changing the cover of the songs but now I have a problem with downloading music
![image](https://user-images.githubusercontent.com/49094075/78150764-063ef000-7438-11ea-9f6d-40b9939a4d27.png)
The download stops in this position and does not move.
Before I had a similar problem, but after downloading music and changing to an mp3 file
changing covers and tags stopped on one of the songs (usually in half).
I only had this problem when I chose to download covers. Only some songs had covers and used playable names such as -.
There is my beatmaps

[otiskujawa's beatmaps.txt](https://github.com/ringosham/Lazer-exporter/files/4416134/otiskujawa.s.beatmaps.txt)

**Comment by ringosham** [comment]
This is going to take some time to debug as there's a lot to download.

**Comment by otiskujawa** [comment]
![image](https://user-images.githubusercontent.com/49094075/78269508-fbed2680-7509-11ea-909e-ca8030f061be.png)
Yes

**Comment by ringosham** [comment]
Sorry for the silence. I finally got time to look at this.

Importing the beatmaps are a total pain due to the beatmap importing system of the game itself is on a half-working state. The game marked them with totally wrong beatmap IDs which not only causes leaderboards to not show up but broke the app as well.

I may need a few more days before I can tackle the issue.

**Comment by otiskujawa** [comment]
Ok, I can wait up to several weeks

**Comment by ringosham** [comment]
It seemed the app failed to read one of the mp3s and the whole thing just crashed.

The audio file reader is not made by me so I can't really fix this without looking deep in others work. I'll make it so that it will skip any unreadable mp3 files for now.

Edit: After spending a bit more time, I found out that apparently the app already does that. It crashed when trying to display the error message.

**Comment by ringosham** [comment]
Please check out the new release.

You may notice a lot of errors popping up in the log.
If it is about errors relating to the audio file, that's likely due to my dependencies are too outdated. I may update those when I have the time.
If it is about audio files not found, blame osu!lazer. Cause that's not supposed to happen.

**Comment by otiskujawa** [comment]
**Can you add skip option for errors ?**
Beatmap 119 AKITO - Sakura Kagetsu has no audio file
NullPointerException : null
Failed processing song: 332 Sigh - Midnight Sun
NullPointerException : null
Failed processing song: 573 Steel Angels - Kiss Kara Hajimaru Miracle
NullPointerException : null
Failed processing song: 648 Dethklok - Duncan Hills Coffee Jingle
NullPointerException : null
Failed processing song: 698 RIZE - Lady Love
NullPointerException : null
Beatmap 73 LM.C - BOYS & GIRLS has no audio file
NullPointerException : null
Failed processing song: 96  - Speed Over Beethoven
InputFormatException : Error while opening file
Beatmap 351167 Kana Hanazawa - Renai Circulation has no audio file
NullPointerException : null
Failed converting song. Keeping ogg format: Let's Dance - Delaney Wolff
it.sauronsoftware.jave.EncoderException : Error while opening codec for output stream #0.0 - maybe incorrect parameters such as bit_rate, rate, width or height
Cannot read album art. Skipping album art for Fire Emblem Theme (Brawl Version) - Shogo Sakai
java.lang.IllegalArgumentException : image == null!

![image](https://user-images.githubusercontent.com/49094075/81050898-1d528100-8ec1-11ea-81f6-a8ed471551a2.png)


**Now the files have been exported but not all have new tags.
Thank you for your help**

**Comment by otiskujawa** [comment]
![image](https://user-images.githubusercontent.com/49094075/81051609-4b849080-8ec2-11ea-89d8-438ed608b308.png)

**Comment by ringosham** [comment]
The app will continue to function despite the errors, meaning it already skips the files affected.
It will just display them just to let you know something went wrong instead of nothing. You can safely ignore them.

About the album arts, this is also normal. Many music players, including Windows itself. Don't like album arts at anything other than 1:1 aspect ratio. They will sometimes outright refuse to read them.

**Comment by ringosham** [comment]
I can't reproduce the missing title and author tags however.

**Comment by otiskujawa** [comment]
Ok 
Finaly i can make .. 32 hours of music in one playlist
![image](https://user-images.githubusercontent.com/49094075/81329557-09fd0c80-909f-11ea-838e-948e13adb324.png)
